name: "Family Expenses Tracker"
description: "A simple family expenses tracker addon."
version: "0.9.23"
slug: "family_expenses_tracker"
init: false
arch:
  - aarch64
  - amd64
  - armv7
map:
  - config:rw
  - share:rw
options: {}
schema: {}
ingress: true
ingress_port: 8000
panel_icon: mdi:finance
panel_title: Family Expenses
