name: "Lufa Farms"
description: "Track your Lufa Farms deliveries in Home Assistant"
version: "0.2.6"
slug: "lufa_farms"
init: false
hassio_api: true
homeassistant_api: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  email: ""
  password: ""
  mqtt_host: ""
  mqtt_port: 1883
  mqtt_username: ""
  mqtt_password: ""
schema:
  email: str
  password: str
  mqtt_host: str?
  mqtt_port: int?
  mqtt_username: str?
  mqtt_password: str?
services:
  - "mqtt:want"

